//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOSWebPortalBgService.MailApi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OvaAccount", Namespace="http://messenger.org/")]
    [System.SerializableAttribute()]
    public partial class OvaAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private double ThresholdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Vendor {
            get {
                return this.VendorField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorField, value) != true)) {
                    this.VendorField = value;
                    this.RaisePropertyChanged("Vendor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((object.ReferenceEquals(this.BalanceField, value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderId {
            get {
                return this.SenderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIdField, value) != true)) {
                    this.SenderIdField = value;
                    this.RaisePropertyChanged("SenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SpId {
            get {
                return this.SpIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SpIdField, value) != true)) {
                    this.SpIdField = value;
                    this.RaisePropertyChanged("SpId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double Threshold {
            get {
                return this.ThresholdField;
            }
            set {
                if ((this.ThresholdField.Equals(value) != true)) {
                    this.ThresholdField = value;
                    this.RaisePropertyChanged("Threshold");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Email", Namespace="http://messenger.org/")]
    [System.SerializableAttribute()]
    public partial class Email : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GreeetingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SchoolOSWebPortalBgService.MailApi.EmailAddress[] MailAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SchoolOSWebPortalBgService.MailApi.Attachment[] AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SchoolOSWebPortalBgService.MailApi.Credentials CredsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Greeeting {
            get {
                return this.GreeetingField;
            }
            set {
                if ((object.ReferenceEquals(this.GreeetingField, value) != true)) {
                    this.GreeetingField = value;
                    this.RaisePropertyChanged("Greeeting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public SchoolOSWebPortalBgService.MailApi.EmailAddress[] MailAddresses {
            get {
                return this.MailAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.MailAddressesField, value) != true)) {
                    this.MailAddressesField = value;
                    this.RaisePropertyChanged("MailAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public SchoolOSWebPortalBgService.MailApi.Attachment[] Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public SchoolOSWebPortalBgService.MailApi.Credentials Creds {
            get {
                return this.CredsField;
            }
            set {
                if ((object.ReferenceEquals(this.CredsField, value) != true)) {
                    this.CredsField = value;
                    this.RaisePropertyChanged("Creds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credentials", Namespace="http://messenger.org/")]
    [System.SerializableAttribute()]
    public partial class Credentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostField;
        
        private int PortField;
        
        private bool DefaultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Host {
            get {
                return this.HostField;
            }
            set {
                if ((object.ReferenceEquals(this.HostField, value) != true)) {
                    this.HostField = value;
                    this.RaisePropertyChanged("Host");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Port {
            get {
                return this.PortField;
            }
            set {
                if ((this.PortField.Equals(value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Default {
            get {
                return this.DefaultField;
            }
            set {
                if ((this.DefaultField.Equals(value) != true)) {
                    this.DefaultField = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailAddress", Namespace="http://messenger.org/")]
    [System.SerializableAttribute()]
    public partial class EmailAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        private SchoolOSWebPortalBgService.MailApi.EmailAddressType AddressTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public SchoolOSWebPortalBgService.MailApi.EmailAddressType AddressType {
            get {
                return this.AddressTypeField;
            }
            set {
                if ((this.AddressTypeField.Equals(value) != true)) {
                    this.AddressTypeField = value;
                    this.RaisePropertyChanged("AddressType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attachment", Namespace="http://messenger.org/")]
    [System.SerializableAttribute()]
    public partial class Attachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AttachmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MimeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ByteArrayField;
        
        private System.DateTime DateCreatedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AttachmentId {
            get {
                return this.AttachmentIdField;
            }
            set {
                if ((this.AttachmentIdField.Equals(value) != true)) {
                    this.AttachmentIdField = value;
                    this.RaisePropertyChanged("AttachmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AttachmentName {
            get {
                return this.AttachmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentNameField, value) != true)) {
                    this.AttachmentNameField = value;
                    this.RaisePropertyChanged("AttachmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MimeType {
            get {
                return this.MimeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MimeTypeField, value) != true)) {
                    this.MimeTypeField = value;
                    this.RaisePropertyChanged("MimeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] ByteArray {
            get {
                return this.ByteArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.ByteArrayField, value) != true)) {
                    this.ByteArrayField = value;
                    this.RaisePropertyChanged("ByteArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailAddressType", Namespace="http://messenger.org/")]
    public enum EmailAddressType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        To = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CarbonCopy = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BlindCarbonCopy = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        From = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://messenger.org/")]
    [System.SerializableAttribute()]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceField, value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Broadcast", Namespace="http://messenger.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SchoolOSWebPortalBgService.MailApi.BroadcastStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SchoolOSWebPortalBgService.MailApi.SmsBroadcast))]
    public partial class Broadcast : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromField;
        
        private SchoolOSWebPortalBgService.MailApi.BroadcastType BroadcastTypeField;
        
        private System.Nullable<int> HourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BroadcastDateField;
        
        private SchoolOSWebPortalBgService.MailApi.MessageType MessageTypeField;
        
        private SchoolOSWebPortalBgService.MailApi.Frequency FrequencyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public SchoolOSWebPortalBgService.MailApi.BroadcastType BroadcastType {
            get {
                return this.BroadcastTypeField;
            }
            set {
                if ((this.BroadcastTypeField.Equals(value) != true)) {
                    this.BroadcastTypeField = value;
                    this.RaisePropertyChanged("BroadcastType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> Hour {
            get {
                return this.HourField;
            }
            set {
                if ((this.HourField.Equals(value) != true)) {
                    this.HourField = value;
                    this.RaisePropertyChanged("Hour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BroadcastDate {
            get {
                return this.BroadcastDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BroadcastDateField, value) != true)) {
                    this.BroadcastDateField = value;
                    this.RaisePropertyChanged("BroadcastDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public SchoolOSWebPortalBgService.MailApi.MessageType MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((this.MessageTypeField.Equals(value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public SchoolOSWebPortalBgService.MailApi.Frequency Frequency {
            get {
                return this.FrequencyField;
            }
            set {
                if ((this.FrequencyField.Equals(value) != true)) {
                    this.FrequencyField = value;
                    this.RaisePropertyChanged("Frequency");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BroadcastStatus", Namespace="http://messenger.org/")]
    [System.SerializableAttribute()]
    public partial class BroadcastStatus : SchoolOSWebPortalBgService.MailApi.Broadcast {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BroadcastIdField;
        
        private int NumberOfReceiversField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SchoolOSWebPortalBgService.MailApi.ArrayOfString ReceiversField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SchoolOSWebPortalBgService.MailApi.ArrayOfString BroadcastDatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BroadcastId {
            get {
                return this.BroadcastIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BroadcastIdField, value) != true)) {
                    this.BroadcastIdField = value;
                    this.RaisePropertyChanged("BroadcastId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumberOfReceivers {
            get {
                return this.NumberOfReceiversField;
            }
            set {
                if ((this.NumberOfReceiversField.Equals(value) != true)) {
                    this.NumberOfReceiversField = value;
                    this.RaisePropertyChanged("NumberOfReceivers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SchoolOSWebPortalBgService.MailApi.ArrayOfString Receivers {
            get {
                return this.ReceiversField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiversField, value) != true)) {
                    this.ReceiversField = value;
                    this.RaisePropertyChanged("Receivers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SchoolOSWebPortalBgService.MailApi.ArrayOfString BroadcastDates {
            get {
                return this.BroadcastDatesField;
            }
            set {
                if ((object.ReferenceEquals(this.BroadcastDatesField, value) != true)) {
                    this.BroadcastDatesField = value;
                    this.RaisePropertyChanged("BroadcastDates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsBroadcast", Namespace="http://messenger.org/")]
    [System.SerializableAttribute()]
    public partial class SmsBroadcast : SchoolOSWebPortalBgService.MailApi.Broadcast {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SchoolOSWebPortalBgService.MailApi.Receiver[] ReceiversField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SchoolOSWebPortalBgService.MailApi.Receiver[] Receivers {
            get {
                return this.ReceiversField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiversField, value) != true)) {
                    this.ReceiversField = value;
                    this.RaisePropertyChanged("Receivers");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BroadcastType", Namespace="http://messenger.org/")]
    public enum BroadcastType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMAIL = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageType", Namespace="http://messenger.org/")]
    public enum MessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Generic = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Personalised = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Frequency", Namespace="http://messenger.org/")]
    public enum Frequency : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NONE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DAILY = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WEEKLY = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MONTHLY = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Receiver", Namespace="http://messenger.org/")]
    [System.SerializableAttribute()]
    public partial class Receiver : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VariablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Variables {
            get {
                return this.VariablesField;
            }
            set {
                if ((object.ReferenceEquals(this.VariablesField, value) != true)) {
                    this.VariablesField = value;
                    this.RaisePropertyChanged("Variables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://messenger.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMS", Namespace="http://messenger.org/")]
    [System.SerializableAttribute()]
    public partial class SMS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorTranIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string VendorTranId {
            get {
                return this.VendorTranIdField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorTranIdField, value) != true)) {
                    this.VendorTranIdField = value;
                    this.RaisePropertyChanged("VendorTranId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Mask {
            get {
                return this.MaskField;
            }
            set {
                if ((object.ReferenceEquals(this.MaskField, value) != true)) {
                    this.MaskField = value;
                    this.RaisePropertyChanged("Mask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Sent {
            get {
                return this.SentField;
            }
            set {
                if ((object.ReferenceEquals(this.SentField, value) != true)) {
                    this.SentField = value;
                    this.RaisePropertyChanged("Sent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceField, value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://messenger.org/", ConfigurationName="MailApi.MessengerSoap")]
    public interface MessengerSoap {
        
        // CODEGEN: Generating message contract since element name acct from namespace http://messenger.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/GetBalance", ReplyAction="*")]
        SchoolOSWebPortalBgService.MailApi.GetBalanceResponse GetBalance(SchoolOSWebPortalBgService.MailApi.GetBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.GetBalanceResponse> GetBalanceAsync(SchoolOSWebPortalBgService.MailApi.GetBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://messenger.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/PostEmail", ReplyAction="*")]
        SchoolOSWebPortalBgService.MailApi.PostEmailResponse PostEmail(SchoolOSWebPortalBgService.MailApi.PostEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/PostEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.PostEmailResponse> PostEmailAsync(SchoolOSWebPortalBgService.MailApi.PostEmailRequest request);
        
        // CODEGEN: Generating message contract since element name reference from namespace http://messenger.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/GetEmailStatus", ReplyAction="*")]
        SchoolOSWebPortalBgService.MailApi.GetEmailStatusResponse GetEmailStatus(SchoolOSWebPortalBgService.MailApi.GetEmailStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/GetEmailStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.GetEmailStatusResponse> GetEmailStatusAsync(SchoolOSWebPortalBgService.MailApi.GetEmailStatusRequest request);
        
        // CODEGEN: Generating message contract since element name broadcast from namespace http://messenger.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/SendSMSBroadcast", ReplyAction="*")]
        SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastResponse SendSMSBroadcast(SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/SendSMSBroadcast", ReplyAction="*")]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastResponse> SendSMSBroadcastAsync(SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastRequest request);
        
        // CODEGEN: Generating message contract since element name reference from namespace http://messenger.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/GetBroadcastStatus", ReplyAction="*")]
        SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusResponse GetBroadcastStatus(SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/GetBroadcastStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusResponse> GetBroadcastStatusAsync(SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusRequest request);
        
        // CODEGEN: Generating message contract since element name receivers from namespace http://messenger.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/AddBroadcastReceivers", ReplyAction="*")]
        SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversResponse AddBroadcastReceivers(SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/AddBroadcastReceivers", ReplyAction="*")]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversResponse> AddBroadcastReceiversAsync(SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversRequest request);
        
        // CODEGEN: Generating message contract since element name broadcastId from namespace http://messenger.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/ChangeBroadcastStatus", ReplyAction="*")]
        SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusResponse ChangeBroadcastStatus(SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/ChangeBroadcastStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusResponse> ChangeBroadcastStatusAsync(SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusRequest request);
        
        // CODEGEN: Generating message contract since element name sms from namespace http://messenger.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/SendSMS", ReplyAction="*")]
        SchoolOSWebPortalBgService.MailApi.SendSMSResponse SendSMS(SchoolOSWebPortalBgService.MailApi.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://messenger.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.SendSMSResponse> SendSMSAsync(SchoolOSWebPortalBgService.MailApi.SendSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalance", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.GetBalanceRequestBody Body;
        
        public GetBalanceRequest() {
        }
        
        public GetBalanceRequest(SchoolOSWebPortalBgService.MailApi.GetBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class GetBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SchoolOSWebPortalBgService.MailApi.OvaAccount acct;
        
        public GetBalanceRequestBody() {
        }
        
        public GetBalanceRequestBody(SchoolOSWebPortalBgService.MailApi.OvaAccount acct) {
            this.acct = acct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalanceResponse", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.GetBalanceResponseBody Body;
        
        public GetBalanceResponse() {
        }
        
        public GetBalanceResponse(SchoolOSWebPortalBgService.MailApi.GetBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class GetBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBalanceResult;
        
        public GetBalanceResponseBody() {
        }
        
        public GetBalanceResponseBody(string GetBalanceResult) {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostEmail", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.PostEmailRequestBody Body;
        
        public PostEmailRequest() {
        }
        
        public PostEmailRequest(SchoolOSWebPortalBgService.MailApi.PostEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class PostEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SchoolOSWebPortalBgService.MailApi.Email email;
        
        public PostEmailRequestBody() {
        }
        
        public PostEmailRequestBody(SchoolOSWebPortalBgService.MailApi.Email email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostEmailResponse", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.PostEmailResponseBody Body;
        
        public PostEmailResponse() {
        }
        
        public PostEmailResponse(SchoolOSWebPortalBgService.MailApi.PostEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class PostEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SchoolOSWebPortalBgService.MailApi.Result PostEmailResult;
        
        public PostEmailResponseBody() {
        }
        
        public PostEmailResponseBody(SchoolOSWebPortalBgService.MailApi.Result PostEmailResult) {
            this.PostEmailResult = PostEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmailStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmailStatus", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.GetEmailStatusRequestBody Body;
        
        public GetEmailStatusRequest() {
        }
        
        public GetEmailStatusRequest(SchoolOSWebPortalBgService.MailApi.GetEmailStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class GetEmailStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reference;
        
        public GetEmailStatusRequestBody() {
        }
        
        public GetEmailStatusRequestBody(string reference) {
            this.reference = reference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmailStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmailStatusResponse", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.GetEmailStatusResponseBody Body;
        
        public GetEmailStatusResponse() {
        }
        
        public GetEmailStatusResponse(SchoolOSWebPortalBgService.MailApi.GetEmailStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class GetEmailStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SchoolOSWebPortalBgService.MailApi.Result GetEmailStatusResult;
        
        public GetEmailStatusResponseBody() {
        }
        
        public GetEmailStatusResponseBody(SchoolOSWebPortalBgService.MailApi.Result GetEmailStatusResult) {
            this.GetEmailStatusResult = GetEmailStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSBroadcastRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSBroadcast", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastRequestBody Body;
        
        public SendSMSBroadcastRequest() {
        }
        
        public SendSMSBroadcastRequest(SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class SendSMSBroadcastRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SchoolOSWebPortalBgService.MailApi.SmsBroadcast broadcast;
        
        public SendSMSBroadcastRequestBody() {
        }
        
        public SendSMSBroadcastRequestBody(SchoolOSWebPortalBgService.MailApi.SmsBroadcast broadcast) {
            this.broadcast = broadcast;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSBroadcastResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSBroadcastResponse", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastResponseBody Body;
        
        public SendSMSBroadcastResponse() {
        }
        
        public SendSMSBroadcastResponse(SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class SendSMSBroadcastResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SchoolOSWebPortalBgService.MailApi.Result SendSMSBroadcastResult;
        
        public SendSMSBroadcastResponseBody() {
        }
        
        public SendSMSBroadcastResponseBody(SchoolOSWebPortalBgService.MailApi.Result SendSMSBroadcastResult) {
            this.SendSMSBroadcastResult = SendSMSBroadcastResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBroadcastStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBroadcastStatus", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusRequestBody Body;
        
        public GetBroadcastStatusRequest() {
        }
        
        public GetBroadcastStatusRequest(SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class GetBroadcastStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reference;
        
        public GetBroadcastStatusRequestBody() {
        }
        
        public GetBroadcastStatusRequestBody(string reference) {
            this.reference = reference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBroadcastStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBroadcastStatusResponse", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusResponseBody Body;
        
        public GetBroadcastStatusResponse() {
        }
        
        public GetBroadcastStatusResponse(SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class GetBroadcastStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SchoolOSWebPortalBgService.MailApi.BroadcastStatus GetBroadcastStatusResult;
        
        public GetBroadcastStatusResponseBody() {
        }
        
        public GetBroadcastStatusResponseBody(SchoolOSWebPortalBgService.MailApi.BroadcastStatus GetBroadcastStatusResult) {
            this.GetBroadcastStatusResult = GetBroadcastStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBroadcastReceiversRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBroadcastReceivers", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversRequestBody Body;
        
        public AddBroadcastReceiversRequest() {
        }
        
        public AddBroadcastReceiversRequest(SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class AddBroadcastReceiversRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SchoolOSWebPortalBgService.MailApi.Receiver[] receivers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string broadcastId;
        
        public AddBroadcastReceiversRequestBody() {
        }
        
        public AddBroadcastReceiversRequestBody(SchoolOSWebPortalBgService.MailApi.Receiver[] receivers, string broadcastId) {
            this.receivers = receivers;
            this.broadcastId = broadcastId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBroadcastReceiversResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBroadcastReceiversResponse", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversResponseBody Body;
        
        public AddBroadcastReceiversResponse() {
        }
        
        public AddBroadcastReceiversResponse(SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class AddBroadcastReceiversResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SchoolOSWebPortalBgService.MailApi.Result AddBroadcastReceiversResult;
        
        public AddBroadcastReceiversResponseBody() {
        }
        
        public AddBroadcastReceiversResponseBody(SchoolOSWebPortalBgService.MailApi.Result AddBroadcastReceiversResult) {
            this.AddBroadcastReceiversResult = AddBroadcastReceiversResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeBroadcastStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeBroadcastStatus", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusRequestBody Body;
        
        public ChangeBroadcastStatusRequest() {
        }
        
        public ChangeBroadcastStatusRequest(SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class ChangeBroadcastStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string broadcastId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool active;
        
        public ChangeBroadcastStatusRequestBody() {
        }
        
        public ChangeBroadcastStatusRequestBody(string broadcastId, bool active) {
            this.broadcastId = broadcastId;
            this.active = active;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeBroadcastStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeBroadcastStatusResponse", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusResponseBody Body;
        
        public ChangeBroadcastStatusResponse() {
        }
        
        public ChangeBroadcastStatusResponse(SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class ChangeBroadcastStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SchoolOSWebPortalBgService.MailApi.Result ChangeBroadcastStatusResult;
        
        public ChangeBroadcastStatusResponseBody() {
        }
        
        public ChangeBroadcastStatusResponseBody(SchoolOSWebPortalBgService.MailApi.Result ChangeBroadcastStatusResult) {
            this.ChangeBroadcastStatusResult = ChangeBroadcastStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(SchoolOSWebPortalBgService.MailApi.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SchoolOSWebPortalBgService.MailApi.SMS sms;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(SchoolOSWebPortalBgService.MailApi.SMS sms) {
            this.sms = sms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://messenger.org/", Order=0)]
        public SchoolOSWebPortalBgService.MailApi.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(SchoolOSWebPortalBgService.MailApi.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://messenger.org/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SchoolOSWebPortalBgService.MailApi.Result SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(SchoolOSWebPortalBgService.MailApi.Result SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessengerSoapChannel : SchoolOSWebPortalBgService.MailApi.MessengerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessengerSoapClient : System.ServiceModel.ClientBase<SchoolOSWebPortalBgService.MailApi.MessengerSoap>, SchoolOSWebPortalBgService.MailApi.MessengerSoap {
        
        public MessengerSoapClient() {
        }
        
        public MessengerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessengerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessengerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessengerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SchoolOSWebPortalBgService.MailApi.GetBalanceResponse SchoolOSWebPortalBgService.MailApi.MessengerSoap.GetBalance(SchoolOSWebPortalBgService.MailApi.GetBalanceRequest request) {
            return base.Channel.GetBalance(request);
        }
        
        public string GetBalance(SchoolOSWebPortalBgService.MailApi.OvaAccount acct) {
            SchoolOSWebPortalBgService.MailApi.GetBalanceRequest inValue = new SchoolOSWebPortalBgService.MailApi.GetBalanceRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.GetBalanceRequestBody();
            inValue.Body.acct = acct;
            SchoolOSWebPortalBgService.MailApi.GetBalanceResponse retVal = ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).GetBalance(inValue);
            return retVal.Body.GetBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.GetBalanceResponse> SchoolOSWebPortalBgService.MailApi.MessengerSoap.GetBalanceAsync(SchoolOSWebPortalBgService.MailApi.GetBalanceRequest request) {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.GetBalanceResponse> GetBalanceAsync(SchoolOSWebPortalBgService.MailApi.OvaAccount acct) {
            SchoolOSWebPortalBgService.MailApi.GetBalanceRequest inValue = new SchoolOSWebPortalBgService.MailApi.GetBalanceRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.GetBalanceRequestBody();
            inValue.Body.acct = acct;
            return ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).GetBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SchoolOSWebPortalBgService.MailApi.PostEmailResponse SchoolOSWebPortalBgService.MailApi.MessengerSoap.PostEmail(SchoolOSWebPortalBgService.MailApi.PostEmailRequest request) {
            return base.Channel.PostEmail(request);
        }
        
        public SchoolOSWebPortalBgService.MailApi.Result PostEmail(SchoolOSWebPortalBgService.MailApi.Email email) {
            SchoolOSWebPortalBgService.MailApi.PostEmailRequest inValue = new SchoolOSWebPortalBgService.MailApi.PostEmailRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.PostEmailRequestBody();
            inValue.Body.email = email;
            SchoolOSWebPortalBgService.MailApi.PostEmailResponse retVal = ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).PostEmail(inValue);
            return retVal.Body.PostEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.PostEmailResponse> SchoolOSWebPortalBgService.MailApi.MessengerSoap.PostEmailAsync(SchoolOSWebPortalBgService.MailApi.PostEmailRequest request) {
            return base.Channel.PostEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.PostEmailResponse> PostEmailAsync(SchoolOSWebPortalBgService.MailApi.Email email) {
            SchoolOSWebPortalBgService.MailApi.PostEmailRequest inValue = new SchoolOSWebPortalBgService.MailApi.PostEmailRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.PostEmailRequestBody();
            inValue.Body.email = email;
            return ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).PostEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SchoolOSWebPortalBgService.MailApi.GetEmailStatusResponse SchoolOSWebPortalBgService.MailApi.MessengerSoap.GetEmailStatus(SchoolOSWebPortalBgService.MailApi.GetEmailStatusRequest request) {
            return base.Channel.GetEmailStatus(request);
        }
        
        public SchoolOSWebPortalBgService.MailApi.Result GetEmailStatus(string reference) {
            SchoolOSWebPortalBgService.MailApi.GetEmailStatusRequest inValue = new SchoolOSWebPortalBgService.MailApi.GetEmailStatusRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.GetEmailStatusRequestBody();
            inValue.Body.reference = reference;
            SchoolOSWebPortalBgService.MailApi.GetEmailStatusResponse retVal = ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).GetEmailStatus(inValue);
            return retVal.Body.GetEmailStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.GetEmailStatusResponse> SchoolOSWebPortalBgService.MailApi.MessengerSoap.GetEmailStatusAsync(SchoolOSWebPortalBgService.MailApi.GetEmailStatusRequest request) {
            return base.Channel.GetEmailStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.GetEmailStatusResponse> GetEmailStatusAsync(string reference) {
            SchoolOSWebPortalBgService.MailApi.GetEmailStatusRequest inValue = new SchoolOSWebPortalBgService.MailApi.GetEmailStatusRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.GetEmailStatusRequestBody();
            inValue.Body.reference = reference;
            return ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).GetEmailStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastResponse SchoolOSWebPortalBgService.MailApi.MessengerSoap.SendSMSBroadcast(SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastRequest request) {
            return base.Channel.SendSMSBroadcast(request);
        }
        
        public SchoolOSWebPortalBgService.MailApi.Result SendSMSBroadcast(SchoolOSWebPortalBgService.MailApi.SmsBroadcast broadcast) {
            SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastRequest inValue = new SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastRequestBody();
            inValue.Body.broadcast = broadcast;
            SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastResponse retVal = ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).SendSMSBroadcast(inValue);
            return retVal.Body.SendSMSBroadcastResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastResponse> SchoolOSWebPortalBgService.MailApi.MessengerSoap.SendSMSBroadcastAsync(SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastRequest request) {
            return base.Channel.SendSMSBroadcastAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastResponse> SendSMSBroadcastAsync(SchoolOSWebPortalBgService.MailApi.SmsBroadcast broadcast) {
            SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastRequest inValue = new SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.SendSMSBroadcastRequestBody();
            inValue.Body.broadcast = broadcast;
            return ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).SendSMSBroadcastAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusResponse SchoolOSWebPortalBgService.MailApi.MessengerSoap.GetBroadcastStatus(SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusRequest request) {
            return base.Channel.GetBroadcastStatus(request);
        }
        
        public SchoolOSWebPortalBgService.MailApi.BroadcastStatus GetBroadcastStatus(string reference) {
            SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusRequest inValue = new SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusRequestBody();
            inValue.Body.reference = reference;
            SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusResponse retVal = ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).GetBroadcastStatus(inValue);
            return retVal.Body.GetBroadcastStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusResponse> SchoolOSWebPortalBgService.MailApi.MessengerSoap.GetBroadcastStatusAsync(SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusRequest request) {
            return base.Channel.GetBroadcastStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusResponse> GetBroadcastStatusAsync(string reference) {
            SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusRequest inValue = new SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.GetBroadcastStatusRequestBody();
            inValue.Body.reference = reference;
            return ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).GetBroadcastStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversResponse SchoolOSWebPortalBgService.MailApi.MessengerSoap.AddBroadcastReceivers(SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversRequest request) {
            return base.Channel.AddBroadcastReceivers(request);
        }
        
        public SchoolOSWebPortalBgService.MailApi.Result AddBroadcastReceivers(SchoolOSWebPortalBgService.MailApi.Receiver[] receivers, string broadcastId) {
            SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversRequest inValue = new SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversRequestBody();
            inValue.Body.receivers = receivers;
            inValue.Body.broadcastId = broadcastId;
            SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversResponse retVal = ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).AddBroadcastReceivers(inValue);
            return retVal.Body.AddBroadcastReceiversResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversResponse> SchoolOSWebPortalBgService.MailApi.MessengerSoap.AddBroadcastReceiversAsync(SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversRequest request) {
            return base.Channel.AddBroadcastReceiversAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversResponse> AddBroadcastReceiversAsync(SchoolOSWebPortalBgService.MailApi.Receiver[] receivers, string broadcastId) {
            SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversRequest inValue = new SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.AddBroadcastReceiversRequestBody();
            inValue.Body.receivers = receivers;
            inValue.Body.broadcastId = broadcastId;
            return ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).AddBroadcastReceiversAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusResponse SchoolOSWebPortalBgService.MailApi.MessengerSoap.ChangeBroadcastStatus(SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusRequest request) {
            return base.Channel.ChangeBroadcastStatus(request);
        }
        
        public SchoolOSWebPortalBgService.MailApi.Result ChangeBroadcastStatus(string broadcastId, bool active) {
            SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusRequest inValue = new SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusRequestBody();
            inValue.Body.broadcastId = broadcastId;
            inValue.Body.active = active;
            SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusResponse retVal = ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).ChangeBroadcastStatus(inValue);
            return retVal.Body.ChangeBroadcastStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusResponse> SchoolOSWebPortalBgService.MailApi.MessengerSoap.ChangeBroadcastStatusAsync(SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusRequest request) {
            return base.Channel.ChangeBroadcastStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusResponse> ChangeBroadcastStatusAsync(string broadcastId, bool active) {
            SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusRequest inValue = new SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.ChangeBroadcastStatusRequestBody();
            inValue.Body.broadcastId = broadcastId;
            inValue.Body.active = active;
            return ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).ChangeBroadcastStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SchoolOSWebPortalBgService.MailApi.SendSMSResponse SchoolOSWebPortalBgService.MailApi.MessengerSoap.SendSMS(SchoolOSWebPortalBgService.MailApi.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public SchoolOSWebPortalBgService.MailApi.Result SendSMS(SchoolOSWebPortalBgService.MailApi.SMS sms) {
            SchoolOSWebPortalBgService.MailApi.SendSMSRequest inValue = new SchoolOSWebPortalBgService.MailApi.SendSMSRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.SendSMSRequestBody();
            inValue.Body.sms = sms;
            SchoolOSWebPortalBgService.MailApi.SendSMSResponse retVal = ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.SendSMSResponse> SchoolOSWebPortalBgService.MailApi.MessengerSoap.SendSMSAsync(SchoolOSWebPortalBgService.MailApi.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SchoolOSWebPortalBgService.MailApi.SendSMSResponse> SendSMSAsync(SchoolOSWebPortalBgService.MailApi.SMS sms) {
            SchoolOSWebPortalBgService.MailApi.SendSMSRequest inValue = new SchoolOSWebPortalBgService.MailApi.SendSMSRequest();
            inValue.Body = new SchoolOSWebPortalBgService.MailApi.SendSMSRequestBody();
            inValue.Body.sms = sms;
            return ((SchoolOSWebPortalBgService.MailApi.MessengerSoap)(this)).SendSMSAsync(inValue);
        }
    }
}
