//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace InterLinkClass.PegPaySchoolsApi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://pegasus.co.ug/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExecuteDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveSchoolOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveStudentOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveSchoolClassOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveSchoolSemesterOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveSchoolStaffOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveClassStreamOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveSystemUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveSubjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveSchoolFeesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveStudentFeesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveMainLinkOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveSubLinkOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveUserTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveMenuOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::InterLinkClass.Properties.Settings.Default.InterLinkClass_PegPaySchoolsApi_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExecuteDataSetCompletedEventHandler ExecuteDataSetCompleted;
        
        /// <remarks/>
        public event SaveSchoolCompletedEventHandler SaveSchoolCompleted;
        
        /// <remarks/>
        public event SaveStudentCompletedEventHandler SaveStudentCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event SaveSchoolClassCompletedEventHandler SaveSchoolClassCompleted;
        
        /// <remarks/>
        public event SaveSchoolSemesterCompletedEventHandler SaveSchoolSemesterCompleted;
        
        /// <remarks/>
        public event SaveSchoolStaffCompletedEventHandler SaveSchoolStaffCompleted;
        
        /// <remarks/>
        public event SaveClassStreamCompletedEventHandler SaveClassStreamCompleted;
        
        /// <remarks/>
        public event SaveSystemUserCompletedEventHandler SaveSystemUserCompleted;
        
        /// <remarks/>
        public event SaveSubjectCompletedEventHandler SaveSubjectCompleted;
        
        /// <remarks/>
        public event SaveSchoolFeesCompletedEventHandler SaveSchoolFeesCompleted;
        
        /// <remarks/>
        public event SaveStudentFeesCompletedEventHandler SaveStudentFeesCompleted;
        
        /// <remarks/>
        public event SaveMainLinkCompletedEventHandler SaveMainLinkCompleted;
        
        /// <remarks/>
        public event SaveSubLinkCompletedEventHandler SaveSubLinkCompleted;
        
        /// <remarks/>
        public event SaveUserTypeCompletedEventHandler SaveUserTypeCompleted;
        
        /// <remarks/>
        public event SaveMenuCompletedEventHandler SaveMenuCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/ExecuteDataSet", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ExecuteDataSet(string storedProc, object[] parameters) {
            object[] results = this.Invoke("ExecuteDataSet", new object[] {
                        storedProc,
                        parameters});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteDataSetAsync(string storedProc, object[] parameters) {
            this.ExecuteDataSetAsync(storedProc, parameters, null);
        }
        
        /// <remarks/>
        public void ExecuteDataSetAsync(string storedProc, object[] parameters, object userState) {
            if ((this.ExecuteDataSetOperationCompleted == null)) {
                this.ExecuteDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteDataSetOperationCompleted);
            }
            this.InvokeAsync("ExecuteDataSet", new object[] {
                        storedProc,
                        parameters}, this.ExecuteDataSetOperationCompleted, userState);
        }
        
        private void OnExecuteDataSetOperationCompleted(object arg) {
            if ((this.ExecuteDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteDataSetCompleted(this, new ExecuteDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/SaveSchool", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveSchool(School sch) {
            object[] results = this.Invoke("SaveSchool", new object[] {
                        sch});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveSchoolAsync(School sch) {
            this.SaveSchoolAsync(sch, null);
        }
        
        /// <remarks/>
        public void SaveSchoolAsync(School sch, object userState) {
            if ((this.SaveSchoolOperationCompleted == null)) {
                this.SaveSchoolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveSchoolOperationCompleted);
            }
            this.InvokeAsync("SaveSchool", new object[] {
                        sch}, this.SaveSchoolOperationCompleted, userState);
        }
        
        private void OnSaveSchoolOperationCompleted(object arg) {
            if ((this.SaveSchoolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveSchoolCompleted(this, new SaveSchoolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/SaveStudent", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveStudent(Student std) {
            object[] results = this.Invoke("SaveStudent", new object[] {
                        std});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveStudentAsync(Student std) {
            this.SaveStudentAsync(std, null);
        }
        
        /// <remarks/>
        public void SaveStudentAsync(Student std, object userState) {
            if ((this.SaveStudentOperationCompleted == null)) {
                this.SaveStudentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveStudentOperationCompleted);
            }
            this.InvokeAsync("SaveStudent", new object[] {
                        std}, this.SaveStudentOperationCompleted, userState);
        }
        
        private void OnSaveStudentOperationCompleted(object arg) {
            if ((this.SaveStudentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveStudentCompleted(this, new SaveStudentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/Login", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SystemUserDetails Login(string Username, string Password) {
            object[] results = this.Invoke("Login", new object[] {
                        Username,
                        Password});
            return ((SystemUserDetails)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string Username, string Password) {
            this.LoginAsync(Username, Password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string Username, string Password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        Username,
                        Password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/SaveSchoolClass", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveSchoolClass(SchoolClass schcls) {
            object[] results = this.Invoke("SaveSchoolClass", new object[] {
                        schcls});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveSchoolClassAsync(SchoolClass schcls) {
            this.SaveSchoolClassAsync(schcls, null);
        }
        
        /// <remarks/>
        public void SaveSchoolClassAsync(SchoolClass schcls, object userState) {
            if ((this.SaveSchoolClassOperationCompleted == null)) {
                this.SaveSchoolClassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveSchoolClassOperationCompleted);
            }
            this.InvokeAsync("SaveSchoolClass", new object[] {
                        schcls}, this.SaveSchoolClassOperationCompleted, userState);
        }
        
        private void OnSaveSchoolClassOperationCompleted(object arg) {
            if ((this.SaveSchoolClassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveSchoolClassCompleted(this, new SaveSchoolClassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/SaveSchoolSemester", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveSchoolSemester(SchoolSemester semester) {
            object[] results = this.Invoke("SaveSchoolSemester", new object[] {
                        semester});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveSchoolSemesterAsync(SchoolSemester semester) {
            this.SaveSchoolSemesterAsync(semester, null);
        }
        
        /// <remarks/>
        public void SaveSchoolSemesterAsync(SchoolSemester semester, object userState) {
            if ((this.SaveSchoolSemesterOperationCompleted == null)) {
                this.SaveSchoolSemesterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveSchoolSemesterOperationCompleted);
            }
            this.InvokeAsync("SaveSchoolSemester", new object[] {
                        semester}, this.SaveSchoolSemesterOperationCompleted, userState);
        }
        
        private void OnSaveSchoolSemesterOperationCompleted(object arg) {
            if ((this.SaveSchoolSemesterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveSchoolSemesterCompleted(this, new SaveSchoolSemesterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/SaveSchoolStaff", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveSchoolStaff(SchoolStaff staff) {
            object[] results = this.Invoke("SaveSchoolStaff", new object[] {
                        staff});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveSchoolStaffAsync(SchoolStaff staff) {
            this.SaveSchoolStaffAsync(staff, null);
        }
        
        /// <remarks/>
        public void SaveSchoolStaffAsync(SchoolStaff staff, object userState) {
            if ((this.SaveSchoolStaffOperationCompleted == null)) {
                this.SaveSchoolStaffOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveSchoolStaffOperationCompleted);
            }
            this.InvokeAsync("SaveSchoolStaff", new object[] {
                        staff}, this.SaveSchoolStaffOperationCompleted, userState);
        }
        
        private void OnSaveSchoolStaffOperationCompleted(object arg) {
            if ((this.SaveSchoolStaffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveSchoolStaffCompleted(this, new SaveSchoolStaffCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/SaveClassStream", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveClassStream(ClassStream stream) {
            object[] results = this.Invoke("SaveClassStream", new object[] {
                        stream});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveClassStreamAsync(ClassStream stream) {
            this.SaveClassStreamAsync(stream, null);
        }
        
        /// <remarks/>
        public void SaveClassStreamAsync(ClassStream stream, object userState) {
            if ((this.SaveClassStreamOperationCompleted == null)) {
                this.SaveClassStreamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveClassStreamOperationCompleted);
            }
            this.InvokeAsync("SaveClassStream", new object[] {
                        stream}, this.SaveClassStreamOperationCompleted, userState);
        }
        
        private void OnSaveClassStreamOperationCompleted(object arg) {
            if ((this.SaveClassStreamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveClassStreamCompleted(this, new SaveClassStreamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/SaveSystemUser", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveSystemUser(SystemUser user) {
            object[] results = this.Invoke("SaveSystemUser", new object[] {
                        user});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveSystemUserAsync(SystemUser user) {
            this.SaveSystemUserAsync(user, null);
        }
        
        /// <remarks/>
        public void SaveSystemUserAsync(SystemUser user, object userState) {
            if ((this.SaveSystemUserOperationCompleted == null)) {
                this.SaveSystemUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveSystemUserOperationCompleted);
            }
            this.InvokeAsync("SaveSystemUser", new object[] {
                        user}, this.SaveSystemUserOperationCompleted, userState);
        }
        
        private void OnSaveSystemUserOperationCompleted(object arg) {
            if ((this.SaveSystemUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveSystemUserCompleted(this, new SaveSystemUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/SaveSubject", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveSubject(Subject sub) {
            object[] results = this.Invoke("SaveSubject", new object[] {
                        sub});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveSubjectAsync(Subject sub) {
            this.SaveSubjectAsync(sub, null);
        }
        
        /// <remarks/>
        public void SaveSubjectAsync(Subject sub, object userState) {
            if ((this.SaveSubjectOperationCompleted == null)) {
                this.SaveSubjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveSubjectOperationCompleted);
            }
            this.InvokeAsync("SaveSubject", new object[] {
                        sub}, this.SaveSubjectOperationCompleted, userState);
        }
        
        private void OnSaveSubjectOperationCompleted(object arg) {
            if ((this.SaveSubjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveSubjectCompleted(this, new SaveSubjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/SaveSchoolFees", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveSchoolFees(SchoolFee fee) {
            object[] results = this.Invoke("SaveSchoolFees", new object[] {
                        fee});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveSchoolFeesAsync(SchoolFee fee) {
            this.SaveSchoolFeesAsync(fee, null);
        }
        
        /// <remarks/>
        public void SaveSchoolFeesAsync(SchoolFee fee, object userState) {
            if ((this.SaveSchoolFeesOperationCompleted == null)) {
                this.SaveSchoolFeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveSchoolFeesOperationCompleted);
            }
            this.InvokeAsync("SaveSchoolFees", new object[] {
                        fee}, this.SaveSchoolFeesOperationCompleted, userState);
        }
        
        private void OnSaveSchoolFeesOperationCompleted(object arg) {
            if ((this.SaveSchoolFeesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveSchoolFeesCompleted(this, new SaveSchoolFeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/SaveStudentFees", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveStudentFees(StudentFee fee) {
            object[] results = this.Invoke("SaveStudentFees", new object[] {
                        fee});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveStudentFeesAsync(StudentFee fee) {
            this.SaveStudentFeesAsync(fee, null);
        }
        
        /// <remarks/>
        public void SaveStudentFeesAsync(StudentFee fee, object userState) {
            if ((this.SaveStudentFeesOperationCompleted == null)) {
                this.SaveStudentFeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveStudentFeesOperationCompleted);
            }
            this.InvokeAsync("SaveStudentFees", new object[] {
                        fee}, this.SaveStudentFeesOperationCompleted, userState);
        }
        
        private void OnSaveStudentFeesOperationCompleted(object arg) {
            if ((this.SaveStudentFeesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveStudentFeesCompleted(this, new SaveStudentFeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/SaveMainLink", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveMainLink(MainLink mainLink) {
            object[] results = this.Invoke("SaveMainLink", new object[] {
                        mainLink});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveMainLinkAsync(MainLink mainLink) {
            this.SaveMainLinkAsync(mainLink, null);
        }
        
        /// <remarks/>
        public void SaveMainLinkAsync(MainLink mainLink, object userState) {
            if ((this.SaveMainLinkOperationCompleted == null)) {
                this.SaveMainLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveMainLinkOperationCompleted);
            }
            this.InvokeAsync("SaveMainLink", new object[] {
                        mainLink}, this.SaveMainLinkOperationCompleted, userState);
        }
        
        private void OnSaveMainLinkOperationCompleted(object arg) {
            if ((this.SaveMainLinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveMainLinkCompleted(this, new SaveMainLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/SaveSubLink", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveSubLink(SubLink sub) {
            object[] results = this.Invoke("SaveSubLink", new object[] {
                        sub});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveSubLinkAsync(SubLink sub) {
            this.SaveSubLinkAsync(sub, null);
        }
        
        /// <remarks/>
        public void SaveSubLinkAsync(SubLink sub, object userState) {
            if ((this.SaveSubLinkOperationCompleted == null)) {
                this.SaveSubLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveSubLinkOperationCompleted);
            }
            this.InvokeAsync("SaveSubLink", new object[] {
                        sub}, this.SaveSubLinkOperationCompleted, userState);
        }
        
        private void OnSaveSubLinkOperationCompleted(object arg) {
            if ((this.SaveSubLinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveSubLinkCompleted(this, new SaveSubLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/SaveUserType", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveUserType(UserType sub) {
            object[] results = this.Invoke("SaveUserType", new object[] {
                        sub});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveUserTypeAsync(UserType sub) {
            this.SaveUserTypeAsync(sub, null);
        }
        
        /// <remarks/>
        public void SaveUserTypeAsync(UserType sub, object userState) {
            if ((this.SaveUserTypeOperationCompleted == null)) {
                this.SaveUserTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveUserTypeOperationCompleted);
            }
            this.InvokeAsync("SaveUserType", new object[] {
                        sub}, this.SaveUserTypeOperationCompleted, userState);
        }
        
        private void OnSaveUserTypeOperationCompleted(object arg) {
            if ((this.SaveUserTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveUserTypeCompleted(this, new SaveUserTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/SaveMenu", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveMenu(MenuItem sub) {
            object[] results = this.Invoke("SaveMenu", new object[] {
                        sub});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveMenuAsync(MenuItem sub) {
            this.SaveMenuAsync(sub, null);
        }
        
        /// <remarks/>
        public void SaveMenuAsync(MenuItem sub, object userState) {
            if ((this.SaveMenuOperationCompleted == null)) {
                this.SaveMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveMenuOperationCompleted);
            }
            this.InvokeAsync("SaveMenu", new object[] {
                        sub}, this.SaveMenuOperationCompleted, userState);
        }
        
        private void OnSaveMenuOperationCompleted(object arg) {
            if ((this.SaveMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveMenuCompleted(this, new SaveMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Status))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemUserDetails))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Request))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StudentFee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SchoolFee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Subject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassStream))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SchoolStaff))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SchoolSemester))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SchoolClass))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemUser))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MainLink))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MenuItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubLink))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Student))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(School))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class Entity {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemUserDetails))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Request))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StudentFee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SchoolFee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Subject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassStream))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SchoolStaff))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SchoolSemester))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SchoolClass))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemUser))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MainLink))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MenuItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubLink))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Student))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(School))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class Status : Entity {
        
        private string statusCodeField;
        
        private string statusDescField;
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDesc {
            get {
                return this.statusDescField;
            }
            set {
                this.statusDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemUserDetails))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class Result : Status {
        
        private string pegPayIDField;
        
        private string thirdPartyIDField;
        
        private string requestIDField;
        
        /// <remarks/>
        public string PegPayID {
            get {
                return this.pegPayIDField;
            }
            set {
                this.pegPayIDField = value;
            }
        }
        
        /// <remarks/>
        public string ThirdPartyID {
            get {
                return this.thirdPartyIDField;
            }
            set {
                this.thirdPartyIDField = value;
            }
        }
        
        /// <remarks/>
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class SystemUserDetails : Result {
        
        private SystemUser userField;
        
        private School schoolDetailsField;
        
        private MenuItem[] userMenuOptionsField;
        
        /// <remarks/>
        public SystemUser User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public School SchoolDetails {
            get {
                return this.schoolDetailsField;
            }
            set {
                this.schoolDetailsField = value;
            }
        }
        
        /// <remarks/>
        public MenuItem[] UserMenuOptions {
            get {
                return this.userMenuOptionsField;
            }
            set {
                this.userMenuOptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class SystemUser : Request {
        
        private string usernameField;
        
        private string userPasswordField;
        
        private string userTypeField;
        
        private string userCategoryField;
        
        private string secretKeyField;
        
        private string approvedByField;
        
        private string profilePicField;
        
        private string fullNameField;
        
        private string isActiveField;
        
        private string emailField;
        
        private string phoneNumberField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string UserPassword {
            get {
                return this.userPasswordField;
            }
            set {
                this.userPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string UserType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        public string UserCategory {
            get {
                return this.userCategoryField;
            }
            set {
                this.userCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string SecretKey {
            get {
                return this.secretKeyField;
            }
            set {
                this.secretKeyField = value;
            }
        }
        
        /// <remarks/>
        public string ApprovedBy {
            get {
                return this.approvedByField;
            }
            set {
                this.approvedByField = value;
            }
        }
        
        /// <remarks/>
        public string ProfilePic {
            get {
                return this.profilePicField;
            }
            set {
                this.profilePicField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StudentFee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SchoolFee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Subject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassStream))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SchoolStaff))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SchoolSemester))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SchoolClass))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemUser))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MainLink))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MenuItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubLink))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Student))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(School))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class Request : Status {
        
        private string vendorCodeField;
        
        private string vendorPasswordField;
        
        private string schoolCodeField;
        
        private string modifiedByField;
        
        /// <remarks/>
        public string VendorCode {
            get {
                return this.vendorCodeField;
            }
            set {
                this.vendorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string VendorPassword {
            get {
                return this.vendorPasswordField;
            }
            set {
                this.vendorPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string SchoolCode {
            get {
                return this.schoolCodeField;
            }
            set {
                this.schoolCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class UserType : Request {
        
        private string userTypeCodeField;
        
        private string userTypeNameField;
        
        /// <remarks/>
        public string UserTypeCode {
            get {
                return this.userTypeCodeField;
            }
            set {
                this.userTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UserTypeName {
            get {
                return this.userTypeNameField;
            }
            set {
                this.userTypeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class StudentFee : Request {
        
        private string studentIDField;
        
        private string classIDField;
        
        private string feeIDField;
        
        /// <remarks/>
        public string StudentID {
            get {
                return this.studentIDField;
            }
            set {
                this.studentIDField = value;
            }
        }
        
        /// <remarks/>
        public string ClassID {
            get {
                return this.classIDField;
            }
            set {
                this.classIDField = value;
            }
        }
        
        /// <remarks/>
        public string FeeID {
            get {
                return this.feeIDField;
            }
            set {
                this.feeIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class SchoolFee : Request {
        
        private string feeNameField;
        
        private string feeIDField;
        
        private string feeAmountField;
        
        private string currencyCodeField;
        
        private string feeCategoryField;
        
        private string feeTypeField;
        
        private string approvedByField;
        
        /// <remarks/>
        public string FeeName {
            get {
                return this.feeNameField;
            }
            set {
                this.feeNameField = value;
            }
        }
        
        /// <remarks/>
        public string FeeID {
            get {
                return this.feeIDField;
            }
            set {
                this.feeIDField = value;
            }
        }
        
        /// <remarks/>
        public string FeeAmount {
            get {
                return this.feeAmountField;
            }
            set {
                this.feeAmountField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string FeeCategory {
            get {
                return this.feeCategoryField;
            }
            set {
                this.feeCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string FeeType {
            get {
                return this.feeTypeField;
            }
            set {
                this.feeTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ApprovedBy {
            get {
                return this.approvedByField;
            }
            set {
                this.approvedByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class Subject : Request {
        
        private string subjectNameField;
        
        private string subjectCodeField;
        
        /// <remarks/>
        public string SubjectName {
            get {
                return this.subjectNameField;
            }
            set {
                this.subjectNameField = value;
            }
        }
        
        /// <remarks/>
        public string SubjectCode {
            get {
                return this.subjectCodeField;
            }
            set {
                this.subjectCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class ClassStream : Request {
        
        private string classCodeField;
        
        private string streamCodeField;
        
        private string streamNameField;
        
        /// <remarks/>
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StreamCode {
            get {
                return this.streamCodeField;
            }
            set {
                this.streamCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StreamName {
            get {
                return this.streamNameField;
            }
            set {
                this.streamNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class SchoolStaff : Request {
        
        private string fullNameField;
        
        private string genderField;
        
        private string staffCategoryField;
        
        private string staffTypeField;
        
        private string staffIDNumberField;
        
        private string pegPayStaffIDNumberField;
        
        private string profilePicField;
        
        private string phoneNumberField;
        
        private string emailField;
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string StaffCategory {
            get {
                return this.staffCategoryField;
            }
            set {
                this.staffCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string StaffType {
            get {
                return this.staffTypeField;
            }
            set {
                this.staffTypeField = value;
            }
        }
        
        /// <remarks/>
        public string StaffIDNumber {
            get {
                return this.staffIDNumberField;
            }
            set {
                this.staffIDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PegPayStaffIDNumber {
            get {
                return this.pegPayStaffIDNumberField;
            }
            set {
                this.pegPayStaffIDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ProfilePic {
            get {
                return this.profilePicField;
            }
            set {
                this.profilePicField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class SchoolSemester : Request {
        
        private string semesterCodeField;
        
        private string startDateField;
        
        private string enddateField;
        
        /// <remarks/>
        public string SemesterCode {
            get {
                return this.semesterCodeField;
            }
            set {
                this.semesterCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string Enddate {
            get {
                return this.enddateField;
            }
            set {
                this.enddateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class SchoolClass : Request {
        
        private string classCodeField;
        
        private string schoolClassNameField;
        
        /// <remarks/>
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SchoolClassName {
            get {
                return this.schoolClassNameField;
            }
            set {
                this.schoolClassNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class MainLink : Request {
        
        private string mainLinkNameField;
        
        private string mainLinkCodeField;
        
        /// <remarks/>
        public string MainLinkName {
            get {
                return this.mainLinkNameField;
            }
            set {
                this.mainLinkNameField = value;
            }
        }
        
        /// <remarks/>
        public string MainLinkCode {
            get {
                return this.mainLinkCodeField;
            }
            set {
                this.mainLinkCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class MenuItem : Request {
        
        private MainLink mainLinkField;
        
        private SubLink[] subLinksField;
        
        private string userTypeField;
        
        private string userCategoryField;
        
        /// <remarks/>
        public MainLink mainLink {
            get {
                return this.mainLinkField;
            }
            set {
                this.mainLinkField = value;
            }
        }
        
        /// <remarks/>
        public SubLink[] subLinks {
            get {
                return this.subLinksField;
            }
            set {
                this.subLinksField = value;
            }
        }
        
        /// <remarks/>
        public string UserType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        public string UserCategory {
            get {
                return this.userCategoryField;
            }
            set {
                this.userCategoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class SubLink : Request {
        
        private string subLinkNameField;
        
        private string subLinkCodeField;
        
        private string uRLField;
        
        /// <remarks/>
        public string SubLinkName {
            get {
                return this.subLinkNameField;
            }
            set {
                this.subLinkNameField = value;
            }
        }
        
        /// <remarks/>
        public string SubLinkCode {
            get {
                return this.subLinkCodeField;
            }
            set {
                this.subLinkCodeField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class Student : Request {
        
        private string studentNumberField;
        
        private string pegPayStudentNumberField;
        
        private string studentNameField;
        
        private string dateOfBirthField;
        
        private string classCodeField;
        
        private string streamCodeField;
        
        private string studentCategoryField;
        
        private string profilePicField;
        
        private string genderField;
        
        private string emailField;
        
        private string phoneNumberField;
        
        /// <remarks/>
        public string StudentNumber {
            get {
                return this.studentNumberField;
            }
            set {
                this.studentNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PegPayStudentNumber {
            get {
                return this.pegPayStudentNumberField;
            }
            set {
                this.pegPayStudentNumberField = value;
            }
        }
        
        /// <remarks/>
        public string StudentName {
            get {
                return this.studentNameField;
            }
            set {
                this.studentNameField = value;
            }
        }
        
        /// <remarks/>
        public string DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StreamCode {
            get {
                return this.streamCodeField;
            }
            set {
                this.streamCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StudentCategory {
            get {
                return this.studentCategoryField;
            }
            set {
                this.studentCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string ProfilePic {
            get {
                return this.profilePicField;
            }
            set {
                this.profilePicField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pegasus.co.ug/")]
    public partial class School : Request {
        
        private string schoolIDField;
        
        private string schoolNameField;
        
        private string unebCentreNumberField;
        
        private string schoolLocationField;
        
        private string schoolEmailField;
        
        private string schoolPhoneField;
        
        private string[] schoolTypeField;
        
        private string[] schoolCategoriesField;
        
        private string plotNoField;
        
        private string roadNameField;
        
        private string subCountyField;
        
        private string districtField;
        
        private string postOfficeBoxField;
        
        private string liquidationBankNameField;
        
        private string liquidationAccountNameField;
        
        private string liquidationAccountNumberField;
        
        private string schoolLogoField;
        
        /// <remarks/>
        public string SchoolID {
            get {
                return this.schoolIDField;
            }
            set {
                this.schoolIDField = value;
            }
        }
        
        /// <remarks/>
        public string SchoolName {
            get {
                return this.schoolNameField;
            }
            set {
                this.schoolNameField = value;
            }
        }
        
        /// <remarks/>
        public string UnebCentreNumber {
            get {
                return this.unebCentreNumberField;
            }
            set {
                this.unebCentreNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SchoolLocation {
            get {
                return this.schoolLocationField;
            }
            set {
                this.schoolLocationField = value;
            }
        }
        
        /// <remarks/>
        public string SchoolEmail {
            get {
                return this.schoolEmailField;
            }
            set {
                this.schoolEmailField = value;
            }
        }
        
        /// <remarks/>
        public string SchoolPhone {
            get {
                return this.schoolPhoneField;
            }
            set {
                this.schoolPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string[] SchoolType {
            get {
                return this.schoolTypeField;
            }
            set {
                this.schoolTypeField = value;
            }
        }
        
        /// <remarks/>
        public string[] SchoolCategories {
            get {
                return this.schoolCategoriesField;
            }
            set {
                this.schoolCategoriesField = value;
            }
        }
        
        /// <remarks/>
        public string PlotNo {
            get {
                return this.plotNoField;
            }
            set {
                this.plotNoField = value;
            }
        }
        
        /// <remarks/>
        public string RoadName {
            get {
                return this.roadNameField;
            }
            set {
                this.roadNameField = value;
            }
        }
        
        /// <remarks/>
        public string SubCounty {
            get {
                return this.subCountyField;
            }
            set {
                this.subCountyField = value;
            }
        }
        
        /// <remarks/>
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public string PostOfficeBox {
            get {
                return this.postOfficeBoxField;
            }
            set {
                this.postOfficeBoxField = value;
            }
        }
        
        /// <remarks/>
        public string LiquidationBankName {
            get {
                return this.liquidationBankNameField;
            }
            set {
                this.liquidationBankNameField = value;
            }
        }
        
        /// <remarks/>
        public string LiquidationAccountName {
            get {
                return this.liquidationAccountNameField;
            }
            set {
                this.liquidationAccountNameField = value;
            }
        }
        
        /// <remarks/>
        public string LiquidationAccountNumber {
            get {
                return this.liquidationAccountNumberField;
            }
            set {
                this.liquidationAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SchoolLogo {
            get {
                return this.schoolLogoField;
            }
            set {
                this.schoolLogoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ExecuteDataSetCompletedEventHandler(object sender, ExecuteDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveSchoolCompletedEventHandler(object sender, SaveSchoolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveSchoolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveSchoolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveStudentCompletedEventHandler(object sender, SaveStudentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveStudentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveStudentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SystemUserDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SystemUserDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveSchoolClassCompletedEventHandler(object sender, SaveSchoolClassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveSchoolClassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveSchoolClassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveSchoolSemesterCompletedEventHandler(object sender, SaveSchoolSemesterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveSchoolSemesterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveSchoolSemesterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveSchoolStaffCompletedEventHandler(object sender, SaveSchoolStaffCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveSchoolStaffCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveSchoolStaffCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveClassStreamCompletedEventHandler(object sender, SaveClassStreamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveClassStreamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveClassStreamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveSystemUserCompletedEventHandler(object sender, SaveSystemUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveSystemUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveSystemUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveSubjectCompletedEventHandler(object sender, SaveSubjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveSubjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveSubjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveSchoolFeesCompletedEventHandler(object sender, SaveSchoolFeesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveSchoolFeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveSchoolFeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveStudentFeesCompletedEventHandler(object sender, SaveStudentFeesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveStudentFeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveStudentFeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveMainLinkCompletedEventHandler(object sender, SaveMainLinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveMainLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveMainLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveSubLinkCompletedEventHandler(object sender, SaveSubLinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveSubLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveSubLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveUserTypeCompletedEventHandler(object sender, SaveUserTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveUserTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveUserTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveMenuCompletedEventHandler(object sender, SaveMenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591