//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CoreBankingLogic.SharedCommonsAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SharedCommonsAPISoap", Namespace="http://pegasus.co.ug/")]
    public partial class SharedCommonsAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllowedImageExtensionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormatUgPhoneNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveCommasFromMoneyStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsValidUgPhoneNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUgPhoneNetworkCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenearetHMACSha256HashOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateUniqueIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateMD5HashOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneratePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneratePinOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsNumericOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsNumericAndAboveZeroOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsValidBooleanOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsValidEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBoolFromStringDefaultsToFalseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIntFromStringDefaultsToZeroOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDigitalSignatureOperationCompleted;
        
        private System.Threading.SendOrPostCallback EncryptTextOperationCompleted;
        
        private System.Threading.SendOrPostCallback DecryptTextOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyDigitalSignatureOperationCompleted;
        
        private System.Threading.SendOrPostCallback DecryptStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback EncryptStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback ByteArrayToStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportDataTableToExcelOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SharedCommonsAPI() {
            this.Url = global::CoreBankingLogic.Properties.Settings.Default.CoreBankingLogic_SharedCommonsAPI_SharedCommonsAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllowedImageExtensionsCompletedEventHandler GetAllowedImageExtensionsCompleted;
        
        /// <remarks/>
        public event FormatUgPhoneNumberCompletedEventHandler FormatUgPhoneNumberCompleted;
        
        /// <remarks/>
        public event RemoveCommasFromMoneyStringCompletedEventHandler RemoveCommasFromMoneyStringCompleted;
        
        /// <remarks/>
        public event IsValidUgPhoneNumberCompletedEventHandler IsValidUgPhoneNumberCompleted;
        
        /// <remarks/>
        public event GetUgPhoneNetworkCodeCompletedEventHandler GetUgPhoneNetworkCodeCompleted;
        
        /// <remarks/>
        public event GenearetHMACSha256HashCompletedEventHandler GenearetHMACSha256HashCompleted;
        
        /// <remarks/>
        public event GenerateUniqueIdCompletedEventHandler GenerateUniqueIdCompleted;
        
        /// <remarks/>
        public event GenerateMD5HashCompletedEventHandler GenerateMD5HashCompleted;
        
        /// <remarks/>
        public event GeneratePasswordCompletedEventHandler GeneratePasswordCompleted;
        
        /// <remarks/>
        public event GeneratePinCompletedEventHandler GeneratePinCompleted;
        
        /// <remarks/>
        public event IsNumericCompletedEventHandler IsNumericCompleted;
        
        /// <remarks/>
        public event IsNumericAndAboveZeroCompletedEventHandler IsNumericAndAboveZeroCompleted;
        
        /// <remarks/>
        public event IsValidBooleanCompletedEventHandler IsValidBooleanCompleted;
        
        /// <remarks/>
        public event IsValidEmailCompletedEventHandler IsValidEmailCompleted;
        
        /// <remarks/>
        public event GetBoolFromStringDefaultsToFalseCompletedEventHandler GetBoolFromStringDefaultsToFalseCompleted;
        
        /// <remarks/>
        public event GetIntFromStringDefaultsToZeroCompletedEventHandler GetIntFromStringDefaultsToZeroCompleted;
        
        /// <remarks/>
        public event GetDigitalSignatureCompletedEventHandler GetDigitalSignatureCompleted;
        
        /// <remarks/>
        public event EncryptTextCompletedEventHandler EncryptTextCompleted;
        
        /// <remarks/>
        public event DecryptTextCompletedEventHandler DecryptTextCompleted;
        
        /// <remarks/>
        public event VerifyDigitalSignatureCompletedEventHandler VerifyDigitalSignatureCompleted;
        
        /// <remarks/>
        public event DecryptStringCompletedEventHandler DecryptStringCompleted;
        
        /// <remarks/>
        public event EncryptStringCompletedEventHandler EncryptStringCompleted;
        
        /// <remarks/>
        public event ByteArrayToStringCompletedEventHandler ByteArrayToStringCompleted;
        
        /// <remarks/>
        public event ExportDataTableToExcelCompletedEventHandler ExportDataTableToExcelCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/GetAllowedImageExtensions", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAllowedImageExtensions() {
            object[] results = this.Invoke("GetAllowedImageExtensions", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllowedImageExtensionsAsync() {
            this.GetAllowedImageExtensionsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllowedImageExtensionsAsync(object userState) {
            if ((this.GetAllowedImageExtensionsOperationCompleted == null)) {
                this.GetAllowedImageExtensionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllowedImageExtensionsOperationCompleted);
            }
            this.InvokeAsync("GetAllowedImageExtensions", new object[0], this.GetAllowedImageExtensionsOperationCompleted, userState);
        }
        
        private void OnGetAllowedImageExtensionsOperationCompleted(object arg) {
            if ((this.GetAllowedImageExtensionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllowedImageExtensionsCompleted(this, new GetAllowedImageExtensionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/FormatUgPhoneNumber", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FormatUgPhoneNumber(string PhoneNumber) {
            object[] results = this.Invoke("FormatUgPhoneNumber", new object[] {
                        PhoneNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormatUgPhoneNumberAsync(string PhoneNumber) {
            this.FormatUgPhoneNumberAsync(PhoneNumber, null);
        }
        
        /// <remarks/>
        public void FormatUgPhoneNumberAsync(string PhoneNumber, object userState) {
            if ((this.FormatUgPhoneNumberOperationCompleted == null)) {
                this.FormatUgPhoneNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormatUgPhoneNumberOperationCompleted);
            }
            this.InvokeAsync("FormatUgPhoneNumber", new object[] {
                        PhoneNumber}, this.FormatUgPhoneNumberOperationCompleted, userState);
        }
        
        private void OnFormatUgPhoneNumberOperationCompleted(object arg) {
            if ((this.FormatUgPhoneNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormatUgPhoneNumberCompleted(this, new FormatUgPhoneNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/RemoveCommasFromMoneyString", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RemoveCommasFromMoneyString(string money) {
            object[] results = this.Invoke("RemoveCommasFromMoneyString", new object[] {
                        money});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveCommasFromMoneyStringAsync(string money) {
            this.RemoveCommasFromMoneyStringAsync(money, null);
        }
        
        /// <remarks/>
        public void RemoveCommasFromMoneyStringAsync(string money, object userState) {
            if ((this.RemoveCommasFromMoneyStringOperationCompleted == null)) {
                this.RemoveCommasFromMoneyStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveCommasFromMoneyStringOperationCompleted);
            }
            this.InvokeAsync("RemoveCommasFromMoneyString", new object[] {
                        money}, this.RemoveCommasFromMoneyStringOperationCompleted, userState);
        }
        
        private void OnRemoveCommasFromMoneyStringOperationCompleted(object arg) {
            if ((this.RemoveCommasFromMoneyStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveCommasFromMoneyStringCompleted(this, new RemoveCommasFromMoneyStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/IsValidUgPhoneNumber", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsValidUgPhoneNumber(string PhoneNumber) {
            object[] results = this.Invoke("IsValidUgPhoneNumber", new object[] {
                        PhoneNumber});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsValidUgPhoneNumberAsync(string PhoneNumber) {
            this.IsValidUgPhoneNumberAsync(PhoneNumber, null);
        }
        
        /// <remarks/>
        public void IsValidUgPhoneNumberAsync(string PhoneNumber, object userState) {
            if ((this.IsValidUgPhoneNumberOperationCompleted == null)) {
                this.IsValidUgPhoneNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsValidUgPhoneNumberOperationCompleted);
            }
            this.InvokeAsync("IsValidUgPhoneNumber", new object[] {
                        PhoneNumber}, this.IsValidUgPhoneNumberOperationCompleted, userState);
        }
        
        private void OnIsValidUgPhoneNumberOperationCompleted(object arg) {
            if ((this.IsValidUgPhoneNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsValidUgPhoneNumberCompleted(this, new IsValidUgPhoneNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/GetUgPhoneNetworkCode", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUgPhoneNetworkCode(string PhoneNumber) {
            object[] results = this.Invoke("GetUgPhoneNetworkCode", new object[] {
                        PhoneNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUgPhoneNetworkCodeAsync(string PhoneNumber) {
            this.GetUgPhoneNetworkCodeAsync(PhoneNumber, null);
        }
        
        /// <remarks/>
        public void GetUgPhoneNetworkCodeAsync(string PhoneNumber, object userState) {
            if ((this.GetUgPhoneNetworkCodeOperationCompleted == null)) {
                this.GetUgPhoneNetworkCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUgPhoneNetworkCodeOperationCompleted);
            }
            this.InvokeAsync("GetUgPhoneNetworkCode", new object[] {
                        PhoneNumber}, this.GetUgPhoneNetworkCodeOperationCompleted, userState);
        }
        
        private void OnGetUgPhoneNetworkCodeOperationCompleted(object arg) {
            if ((this.GetUgPhoneNetworkCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUgPhoneNetworkCodeCompleted(this, new GetUgPhoneNetworkCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/GenearetHMACSha256Hash", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenearetHMACSha256Hash(string secretPresharedKey, string message) {
            object[] results = this.Invoke("GenearetHMACSha256Hash", new object[] {
                        secretPresharedKey,
                        message});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenearetHMACSha256HashAsync(string secretPresharedKey, string message) {
            this.GenearetHMACSha256HashAsync(secretPresharedKey, message, null);
        }
        
        /// <remarks/>
        public void GenearetHMACSha256HashAsync(string secretPresharedKey, string message, object userState) {
            if ((this.GenearetHMACSha256HashOperationCompleted == null)) {
                this.GenearetHMACSha256HashOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenearetHMACSha256HashOperationCompleted);
            }
            this.InvokeAsync("GenearetHMACSha256Hash", new object[] {
                        secretPresharedKey,
                        message}, this.GenearetHMACSha256HashOperationCompleted, userState);
        }
        
        private void OnGenearetHMACSha256HashOperationCompleted(object arg) {
            if ((this.GenearetHMACSha256HashCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenearetHMACSha256HashCompleted(this, new GenearetHMACSha256HashCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/GenerateUniqueId", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerateUniqueId(string LeadString) {
            object[] results = this.Invoke("GenerateUniqueId", new object[] {
                        LeadString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateUniqueIdAsync(string LeadString) {
            this.GenerateUniqueIdAsync(LeadString, null);
        }
        
        /// <remarks/>
        public void GenerateUniqueIdAsync(string LeadString, object userState) {
            if ((this.GenerateUniqueIdOperationCompleted == null)) {
                this.GenerateUniqueIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateUniqueIdOperationCompleted);
            }
            this.InvokeAsync("GenerateUniqueId", new object[] {
                        LeadString}, this.GenerateUniqueIdOperationCompleted, userState);
        }
        
        private void OnGenerateUniqueIdOperationCompleted(object arg) {
            if ((this.GenerateUniqueIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateUniqueIdCompleted(this, new GenerateUniqueIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/GenerateMD5Hash", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerateMD5Hash(string input) {
            object[] results = this.Invoke("GenerateMD5Hash", new object[] {
                        input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateMD5HashAsync(string input) {
            this.GenerateMD5HashAsync(input, null);
        }
        
        /// <remarks/>
        public void GenerateMD5HashAsync(string input, object userState) {
            if ((this.GenerateMD5HashOperationCompleted == null)) {
                this.GenerateMD5HashOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateMD5HashOperationCompleted);
            }
            this.InvokeAsync("GenerateMD5Hash", new object[] {
                        input}, this.GenerateMD5HashOperationCompleted, userState);
        }
        
        private void OnGenerateMD5HashOperationCompleted(object arg) {
            if ((this.GenerateMD5HashCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateMD5HashCompleted(this, new GenerateMD5HashCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/GeneratePassword", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GeneratePassword() {
            object[] results = this.Invoke("GeneratePassword", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GeneratePasswordAsync() {
            this.GeneratePasswordAsync(null);
        }
        
        /// <remarks/>
        public void GeneratePasswordAsync(object userState) {
            if ((this.GeneratePasswordOperationCompleted == null)) {
                this.GeneratePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneratePasswordOperationCompleted);
            }
            this.InvokeAsync("GeneratePassword", new object[0], this.GeneratePasswordOperationCompleted, userState);
        }
        
        private void OnGeneratePasswordOperationCompleted(object arg) {
            if ((this.GeneratePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneratePasswordCompleted(this, new GeneratePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/GeneratePin", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GeneratePin() {
            object[] results = this.Invoke("GeneratePin", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GeneratePinAsync() {
            this.GeneratePinAsync(null);
        }
        
        /// <remarks/>
        public void GeneratePinAsync(object userState) {
            if ((this.GeneratePinOperationCompleted == null)) {
                this.GeneratePinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneratePinOperationCompleted);
            }
            this.InvokeAsync("GeneratePin", new object[0], this.GeneratePinOperationCompleted, userState);
        }
        
        private void OnGeneratePinOperationCompleted(object arg) {
            if ((this.GeneratePinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneratePinCompleted(this, new GeneratePinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/IsNumeric", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsNumeric(string Amount) {
            object[] results = this.Invoke("IsNumeric", new object[] {
                        Amount});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsNumericAsync(string Amount) {
            this.IsNumericAsync(Amount, null);
        }
        
        /// <remarks/>
        public void IsNumericAsync(string Amount, object userState) {
            if ((this.IsNumericOperationCompleted == null)) {
                this.IsNumericOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsNumericOperationCompleted);
            }
            this.InvokeAsync("IsNumeric", new object[] {
                        Amount}, this.IsNumericOperationCompleted, userState);
        }
        
        private void OnIsNumericOperationCompleted(object arg) {
            if ((this.IsNumericCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsNumericCompleted(this, new IsNumericCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/IsNumericAndAboveZero", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsNumericAndAboveZero(string Amount) {
            object[] results = this.Invoke("IsNumericAndAboveZero", new object[] {
                        Amount});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsNumericAndAboveZeroAsync(string Amount) {
            this.IsNumericAndAboveZeroAsync(Amount, null);
        }
        
        /// <remarks/>
        public void IsNumericAndAboveZeroAsync(string Amount, object userState) {
            if ((this.IsNumericAndAboveZeroOperationCompleted == null)) {
                this.IsNumericAndAboveZeroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsNumericAndAboveZeroOperationCompleted);
            }
            this.InvokeAsync("IsNumericAndAboveZero", new object[] {
                        Amount}, this.IsNumericAndAboveZeroOperationCompleted, userState);
        }
        
        private void OnIsNumericAndAboveZeroOperationCompleted(object arg) {
            if ((this.IsNumericAndAboveZeroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsNumericAndAboveZeroCompleted(this, new IsNumericAndAboveZeroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/IsValidBoolean", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsValidBoolean(string p) {
            object[] results = this.Invoke("IsValidBoolean", new object[] {
                        p});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsValidBooleanAsync(string p) {
            this.IsValidBooleanAsync(p, null);
        }
        
        /// <remarks/>
        public void IsValidBooleanAsync(string p, object userState) {
            if ((this.IsValidBooleanOperationCompleted == null)) {
                this.IsValidBooleanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsValidBooleanOperationCompleted);
            }
            this.InvokeAsync("IsValidBoolean", new object[] {
                        p}, this.IsValidBooleanOperationCompleted, userState);
        }
        
        private void OnIsValidBooleanOperationCompleted(object arg) {
            if ((this.IsValidBooleanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsValidBooleanCompleted(this, new IsValidBooleanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/IsValidEmail", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsValidEmail(string email) {
            object[] results = this.Invoke("IsValidEmail", new object[] {
                        email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsValidEmailAsync(string email) {
            this.IsValidEmailAsync(email, null);
        }
        
        /// <remarks/>
        public void IsValidEmailAsync(string email, object userState) {
            if ((this.IsValidEmailOperationCompleted == null)) {
                this.IsValidEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsValidEmailOperationCompleted);
            }
            this.InvokeAsync("IsValidEmail", new object[] {
                        email}, this.IsValidEmailOperationCompleted, userState);
        }
        
        private void OnIsValidEmailOperationCompleted(object arg) {
            if ((this.IsValidEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsValidEmailCompleted(this, new IsValidEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/GetBoolFromStringDefaultsToFalse", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetBoolFromStringDefaultsToFalse(string text) {
            object[] results = this.Invoke("GetBoolFromStringDefaultsToFalse", new object[] {
                        text});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetBoolFromStringDefaultsToFalseAsync(string text) {
            this.GetBoolFromStringDefaultsToFalseAsync(text, null);
        }
        
        /// <remarks/>
        public void GetBoolFromStringDefaultsToFalseAsync(string text, object userState) {
            if ((this.GetBoolFromStringDefaultsToFalseOperationCompleted == null)) {
                this.GetBoolFromStringDefaultsToFalseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBoolFromStringDefaultsToFalseOperationCompleted);
            }
            this.InvokeAsync("GetBoolFromStringDefaultsToFalse", new object[] {
                        text}, this.GetBoolFromStringDefaultsToFalseOperationCompleted, userState);
        }
        
        private void OnGetBoolFromStringDefaultsToFalseOperationCompleted(object arg) {
            if ((this.GetBoolFromStringDefaultsToFalseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBoolFromStringDefaultsToFalseCompleted(this, new GetBoolFromStringDefaultsToFalseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/GetIntFromStringDefaultsToZero", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetIntFromStringDefaultsToZero(string text) {
            object[] results = this.Invoke("GetIntFromStringDefaultsToZero", new object[] {
                        text});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetIntFromStringDefaultsToZeroAsync(string text) {
            this.GetIntFromStringDefaultsToZeroAsync(text, null);
        }
        
        /// <remarks/>
        public void GetIntFromStringDefaultsToZeroAsync(string text, object userState) {
            if ((this.GetIntFromStringDefaultsToZeroOperationCompleted == null)) {
                this.GetIntFromStringDefaultsToZeroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIntFromStringDefaultsToZeroOperationCompleted);
            }
            this.InvokeAsync("GetIntFromStringDefaultsToZero", new object[] {
                        text}, this.GetIntFromStringDefaultsToZeroOperationCompleted, userState);
        }
        
        private void OnGetIntFromStringDefaultsToZeroOperationCompleted(object arg) {
            if ((this.GetIntFromStringDefaultsToZeroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIntFromStringDefaultsToZeroCompleted(this, new GetIntFromStringDefaultsToZeroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/GetDigitalSignature", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDigitalSignature(string dataToSign, string PathToPrivateKey) {
            object[] results = this.Invoke("GetDigitalSignature", new object[] {
                        dataToSign,
                        PathToPrivateKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDigitalSignatureAsync(string dataToSign, string PathToPrivateKey) {
            this.GetDigitalSignatureAsync(dataToSign, PathToPrivateKey, null);
        }
        
        /// <remarks/>
        public void GetDigitalSignatureAsync(string dataToSign, string PathToPrivateKey, object userState) {
            if ((this.GetDigitalSignatureOperationCompleted == null)) {
                this.GetDigitalSignatureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDigitalSignatureOperationCompleted);
            }
            this.InvokeAsync("GetDigitalSignature", new object[] {
                        dataToSign,
                        PathToPrivateKey}, this.GetDigitalSignatureOperationCompleted, userState);
        }
        
        private void OnGetDigitalSignatureOperationCompleted(object arg) {
            if ((this.GetDigitalSignatureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDigitalSignatureCompleted(this, new GetDigitalSignatureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/EncryptText", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EncryptText(string plainText, string PathToPrivateKey) {
            object[] results = this.Invoke("EncryptText", new object[] {
                        plainText,
                        PathToPrivateKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EncryptTextAsync(string plainText, string PathToPrivateKey) {
            this.EncryptTextAsync(plainText, PathToPrivateKey, null);
        }
        
        /// <remarks/>
        public void EncryptTextAsync(string plainText, string PathToPrivateKey, object userState) {
            if ((this.EncryptTextOperationCompleted == null)) {
                this.EncryptTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEncryptTextOperationCompleted);
            }
            this.InvokeAsync("EncryptText", new object[] {
                        plainText,
                        PathToPrivateKey}, this.EncryptTextOperationCompleted, userState);
        }
        
        private void OnEncryptTextOperationCompleted(object arg) {
            if ((this.EncryptTextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EncryptTextCompleted(this, new EncryptTextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/DecryptText", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DecryptText(string plainText, string PathToPrivateKey) {
            object[] results = this.Invoke("DecryptText", new object[] {
                        plainText,
                        PathToPrivateKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DecryptTextAsync(string plainText, string PathToPrivateKey) {
            this.DecryptTextAsync(plainText, PathToPrivateKey, null);
        }
        
        /// <remarks/>
        public void DecryptTextAsync(string plainText, string PathToPrivateKey, object userState) {
            if ((this.DecryptTextOperationCompleted == null)) {
                this.DecryptTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDecryptTextOperationCompleted);
            }
            this.InvokeAsync("DecryptText", new object[] {
                        plainText,
                        PathToPrivateKey}, this.DecryptTextOperationCompleted, userState);
        }
        
        private void OnDecryptTextOperationCompleted(object arg) {
            if ((this.DecryptTextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DecryptTextCompleted(this, new DecryptTextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/VerifyDigitalSignature", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerifyDigitalSignature(string data, string digitalSignature, string pathToPublicKey) {
            object[] results = this.Invoke("VerifyDigitalSignature", new object[] {
                        data,
                        digitalSignature,
                        pathToPublicKey});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyDigitalSignatureAsync(string data, string digitalSignature, string pathToPublicKey) {
            this.VerifyDigitalSignatureAsync(data, digitalSignature, pathToPublicKey, null);
        }
        
        /// <remarks/>
        public void VerifyDigitalSignatureAsync(string data, string digitalSignature, string pathToPublicKey, object userState) {
            if ((this.VerifyDigitalSignatureOperationCompleted == null)) {
                this.VerifyDigitalSignatureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyDigitalSignatureOperationCompleted);
            }
            this.InvokeAsync("VerifyDigitalSignature", new object[] {
                        data,
                        digitalSignature,
                        pathToPublicKey}, this.VerifyDigitalSignatureOperationCompleted, userState);
        }
        
        private void OnVerifyDigitalSignatureOperationCompleted(object arg) {
            if ((this.VerifyDigitalSignatureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyDigitalSignatureCompleted(this, new VerifyDigitalSignatureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/DecryptString", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DecryptString(string encryptedText, string Key) {
            object[] results = this.Invoke("DecryptString", new object[] {
                        encryptedText,
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DecryptStringAsync(string encryptedText, string Key) {
            this.DecryptStringAsync(encryptedText, Key, null);
        }
        
        /// <remarks/>
        public void DecryptStringAsync(string encryptedText, string Key, object userState) {
            if ((this.DecryptStringOperationCompleted == null)) {
                this.DecryptStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDecryptStringOperationCompleted);
            }
            this.InvokeAsync("DecryptString", new object[] {
                        encryptedText,
                        Key}, this.DecryptStringOperationCompleted, userState);
        }
        
        private void OnDecryptStringOperationCompleted(object arg) {
            if ((this.DecryptStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DecryptStringCompleted(this, new DecryptStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/EncryptString", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EncryptString(string plainText, string Key) {
            object[] results = this.Invoke("EncryptString", new object[] {
                        plainText,
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EncryptStringAsync(string plainText, string Key) {
            this.EncryptStringAsync(plainText, Key, null);
        }
        
        /// <remarks/>
        public void EncryptStringAsync(string plainText, string Key, object userState) {
            if ((this.EncryptStringOperationCompleted == null)) {
                this.EncryptStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEncryptStringOperationCompleted);
            }
            this.InvokeAsync("EncryptString", new object[] {
                        plainText,
                        Key}, this.EncryptStringOperationCompleted, userState);
        }
        
        private void OnEncryptStringOperationCompleted(object arg) {
            if ((this.EncryptStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EncryptStringCompleted(this, new EncryptStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/ByteArrayToString", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ByteArrayToString([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] ba) {
            object[] results = this.Invoke("ByteArrayToString", new object[] {
                        ba});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ByteArrayToStringAsync(byte[] ba) {
            this.ByteArrayToStringAsync(ba, null);
        }
        
        /// <remarks/>
        public void ByteArrayToStringAsync(byte[] ba, object userState) {
            if ((this.ByteArrayToStringOperationCompleted == null)) {
                this.ByteArrayToStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnByteArrayToStringOperationCompleted);
            }
            this.InvokeAsync("ByteArrayToString", new object[] {
                        ba}, this.ByteArrayToStringOperationCompleted, userState);
        }
        
        private void OnByteArrayToStringOperationCompleted(object arg) {
            if ((this.ByteArrayToStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ByteArrayToStringCompleted(this, new ByteArrayToStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pegasus.co.ug/ExportDataTableToExcel", RequestNamespace="http://pegasus.co.ug/", ResponseNamespace="http://pegasus.co.ug/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExportDataTableToExcel(System.Data.DataTable dt, string path) {
            object[] results = this.Invoke("ExportDataTableToExcel", new object[] {
                        dt,
                        path});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExportDataTableToExcelAsync(System.Data.DataTable dt, string path) {
            this.ExportDataTableToExcelAsync(dt, path, null);
        }
        
        /// <remarks/>
        public void ExportDataTableToExcelAsync(System.Data.DataTable dt, string path, object userState) {
            if ((this.ExportDataTableToExcelOperationCompleted == null)) {
                this.ExportDataTableToExcelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportDataTableToExcelOperationCompleted);
            }
            this.InvokeAsync("ExportDataTableToExcel", new object[] {
                        dt,
                        path}, this.ExportDataTableToExcelOperationCompleted, userState);
        }
        
        private void OnExportDataTableToExcelOperationCompleted(object arg) {
            if ((this.ExportDataTableToExcelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportDataTableToExcelCompleted(this, new ExportDataTableToExcelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAllowedImageExtensionsCompletedEventHandler(object sender, GetAllowedImageExtensionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllowedImageExtensionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllowedImageExtensionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void FormatUgPhoneNumberCompletedEventHandler(object sender, FormatUgPhoneNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormatUgPhoneNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormatUgPhoneNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RemoveCommasFromMoneyStringCompletedEventHandler(object sender, RemoveCommasFromMoneyStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveCommasFromMoneyStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveCommasFromMoneyStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void IsValidUgPhoneNumberCompletedEventHandler(object sender, IsValidUgPhoneNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsValidUgPhoneNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsValidUgPhoneNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetUgPhoneNetworkCodeCompletedEventHandler(object sender, GetUgPhoneNetworkCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUgPhoneNetworkCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUgPhoneNetworkCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GenearetHMACSha256HashCompletedEventHandler(object sender, GenearetHMACSha256HashCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenearetHMACSha256HashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenearetHMACSha256HashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GenerateUniqueIdCompletedEventHandler(object sender, GenerateUniqueIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateUniqueIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateUniqueIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GenerateMD5HashCompletedEventHandler(object sender, GenerateMD5HashCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateMD5HashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateMD5HashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GeneratePasswordCompletedEventHandler(object sender, GeneratePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeneratePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeneratePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GeneratePinCompletedEventHandler(object sender, GeneratePinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeneratePinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeneratePinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void IsNumericCompletedEventHandler(object sender, IsNumericCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsNumericCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsNumericCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void IsNumericAndAboveZeroCompletedEventHandler(object sender, IsNumericAndAboveZeroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsNumericAndAboveZeroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsNumericAndAboveZeroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void IsValidBooleanCompletedEventHandler(object sender, IsValidBooleanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsValidBooleanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsValidBooleanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void IsValidEmailCompletedEventHandler(object sender, IsValidEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsValidEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsValidEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetBoolFromStringDefaultsToFalseCompletedEventHandler(object sender, GetBoolFromStringDefaultsToFalseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBoolFromStringDefaultsToFalseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBoolFromStringDefaultsToFalseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetIntFromStringDefaultsToZeroCompletedEventHandler(object sender, GetIntFromStringDefaultsToZeroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIntFromStringDefaultsToZeroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIntFromStringDefaultsToZeroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetDigitalSignatureCompletedEventHandler(object sender, GetDigitalSignatureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDigitalSignatureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDigitalSignatureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void EncryptTextCompletedEventHandler(object sender, EncryptTextCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncryptTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EncryptTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DecryptTextCompletedEventHandler(object sender, DecryptTextCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DecryptTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DecryptTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void VerifyDigitalSignatureCompletedEventHandler(object sender, VerifyDigitalSignatureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyDigitalSignatureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyDigitalSignatureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DecryptStringCompletedEventHandler(object sender, DecryptStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DecryptStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DecryptStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void EncryptStringCompletedEventHandler(object sender, EncryptStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncryptStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EncryptStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ByteArrayToStringCompletedEventHandler(object sender, ByteArrayToStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ByteArrayToStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ByteArrayToStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ExportDataTableToExcelCompletedEventHandler(object sender, ExportDataTableToExcelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportDataTableToExcelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportDataTableToExcelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591